name: Update packages
on:
    schedule:
        - cron: '0 2 * * *'
jobs:
    update:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - run: npm ci
            - run: npm update --save
            - name: git status
              id: git_status
              run: '[ -n "`git status -s`" ]'
              continue-on-error: true
            - run: npm run build
              if: steps.git_status.outcome == 'success'
            - run: npm test --lint -- --silent
              if: steps.git_status.outcome == 'success'
            - name: Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update package
              if: steps.git_status.outcome == 'success'
